# configure with params from the docs: 
# https://influxdb-client.readthedocs.io/en/latest/api.html#influxdbclient

influxdb:
  client:
    url: http://localhost:8086/
    token: token
    org: org
    bucket_name: health
  write_points:
    batch_size: 1000
